CREATE DATABASE Susys;

CREATE TABLE usuarios
(
    uid SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    usuario VARCHAR(50) UNIQUE NOT NULL,
    contra VARCHAR(255) NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    verificado BOOLEAN DEFAULT FALSE NOT NULL,
    admin BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE productos
(
    pid SERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    img VARCHAR(255) NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE carrito
(
    cid SERIAL PRIMARY KEY,
    cantidad SMALLINT DEFAULT 1,
    uid INT REFERENCES usuarios(uid),
    pid INT REFERENCES productos(pid)
);
